apiVersion: cache.tongdun.net/v1alpha1
kind: RedisCluster
metadata:
  name: redis-cluster-trump
  namespace: redis
spec:
  app: cluster-trump
  capacity: 32768
  dc: hz
  env: demo
  image: tongduncloud/redis-cluster:0.2
  monitorimage: tongduncloud/redis-exporter:1.0
  netmode: ClusterIP
  proxyimage: tongduncloud/predixy:1.0
  proxysecret: "123"
  realname: demo
  secret: abc
  size: 3
  storageclass: ""
  vip: 172.17.128.8
